# Generated by Django 5.0.6 on 2025-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Администратор'),
                    ('staff', 'Персонал'),
                    ('user', 'Пользователь'),
                ],
                default='user',
                max_length=20,
                verbose_name='Роль',
            ),
        ),
    ]
