# Generated by Django 5.0.6 on 2025-09-25 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'action',
                    models.CharField(max_length=100, verbose_name='Действие'),
                ),
                (
                    'employee',
                    models.CharField(
                        blank=True, max_length=200, verbose_name='Сотрудник'
                    ),
                ),
                (
                    'ip',
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name='IP'
                    ),
                ),
                (
                    'user_agent',
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name='User-Agent',
                    ),
                ),
                (
                    'timestamp',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Время'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'last_name',
                    models.CharField(max_length=100, verbose_name='Фамилия'),
                ),
                (
                    'first_name',
                    models.CharField(max_length=100, verbose_name='Имя'),
                ),
                (
                    'patronymic',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Отчество',
                    ),
                ),
                (
                    'note_date',
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name='Дата служебной записки',
                    ),
                ),
                (
                    'note_number',
                    models.CharField(
                        max_length=50, verbose_name='Номер служебной записки'
                    ),
                ),
                (
                    'login',
                    models.CharField(
                        max_length=150, unique=True, verbose_name='Логин'
                    ),
                ),
                (
                    'password',
                    models.CharField(
                        max_length=128,
                        verbose_name='Пароль (хранится открытым текстом по ТЗ)',
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('create', 'Создание'),
                            ('block', 'Блокировка'),
                        ],
                        default='create',
                        max_length=10,
                        verbose_name='Действие',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Работает'),
                            ('blocked', 'Заблокирован'),
                        ],
                        default='active',
                        max_length=10,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name='Имя учётки (если неизвестен пользователь)',
                    ),
                ),
                (
                    'success',
                    models.BooleanField(default=False, verbose_name='Успех'),
                ),
                (
                    'ip',
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name='IP'
                    ),
                ),
                (
                    'user_agent',
                    models.TextField(
                        blank=True, null=True, verbose_name='User-Agent'
                    ),
                ),
                (
                    'timestamp',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Время'
                    ),
                ),
            ],
            options={
                'verbose_name': 'История входов',
                'verbose_name_plural': 'История входов',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'uppercase',
                    models.PositiveIntegerField(
                        default=1, verbose_name='Кол-во заглавных'
                    ),
                ),
                (
                    'lowercase',
                    models.PositiveIntegerField(
                        default=1, verbose_name='Кол-во строчных'
                    ),
                ),
                (
                    'digits',
                    models.PositiveIntegerField(
                        default=1, verbose_name='Кол-во цифр'
                    ),
                ),
                (
                    'symbols',
                    models.PositiveIntegerField(
                        default=1, verbose_name='Кол-во символов'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Политика паролей',
                'verbose_name_plural': 'Политика паролей',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=150, verbose_name='Регион (код и название)'
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        max_length=2,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^\\d{2}$',
                                'Код региона должен быть двухзначным',
                            )
                        ],
                        verbose_name='Код региона',
                    ),
                ),
            ],
        ),
    ]
