# Generated by Django 5.0.6 on 2025-09-25 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='region_code',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='as_code',
                to='employees.region',
                verbose_name='Код региона',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='region_name',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='as_name',
                to='employees.region',
                verbose_name='Регион',
            ),
        ),
    ]
