# Generated by Django 5.0.6 on 2025-09-26 07:22

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AlterModelOptions(
            name='region',
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='allowed_symbols',
            field=models.CharField(
                default='!@#$%^&*()-_=+<>?',
                help_text='Только ASCII-символы, без пробелов и кириллицы.',
                max_length=100,
                validators=[employees.models.validate_allowed_symbols],
                verbose_name='Разрешённые спецсимволы',
            ),
        ),
    ]
