# Generated by Django 5.0.6 on 2025-09-26 07:29

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'employees',
            '0003_alter_employee_options_alter_region_options_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='note_date',
            field=models.DateField(
                blank=True,
                null=True,
                validators=[employees.models.validate_not_future],
                verbose_name='Дата служебной записки',
            ),
        ),
    ]
